project:
  type: website

website:
  title: "Adrien Website"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "CV" 
        href: https://github.com/adrien-fillon/CV
      - publications.qmd
      - talks.qmd
      - Podcast.qmd
      - metaanalysis.qmd
      - blog.qmd
      - Newsletter.qmd
  twitter-card: true
  sidebar:
    tools:
      - icon: twitter
        href: https://twitter.com/adfillon
      - icon: instagram
        href: https://www.instagram.com/docteurpapers/
      - icon: linkedin
        href: https://www.linkedin.com/in/adrien-fillon-a78010107/


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

