---
title: "Publications"
comments: false
bibliography: references.bib
csl: apa-6th-edition.csl
---

---
nocite: |
  @yeung_experimental_2021, @fillon_correlational_2021, @fillon_how_2021, @fillon_asymmetries_2021, @jaubertsara_vicarious_2020, @fillon_effectiveness_2020, @fillon_personal_2021, @fillon_impact_2021, @brick_self-interest_2021, @parsons_community-sourced_2022, @fillon_exceptionality_2022, @fillon_people_2022, @fillon_evaluations_2022, @jaubert_dissonance_2021, @fillon_slow_2021,@fillon_colloque_2021
---
# 2023

*Fillon, A., *Strauch, L., & Feldman, G. (2023). Evaluations of action and inaction decision-makers in risky decisions resulting in negative outcomes: Inaction agents are preferred to and perceived as more competent and normative than action agents. Collabra:Psychology.
[Preprint](https://www.researchgate.net/publication/369593935_Evaluations_of_action_and_inaction_decision-makers_in_risky_decisions_resulting_in_negative_outcomes_Inaction_agents_are_preferred_to_and_perceived_as_more_competent_and_normative_than_action_agents) [Open materials/data/code](https://osf.io/a8e4d/) [Open access]

# 2022

Parsons, S., Azevedo, F., Elsherif, M.M. et al. A community-sourced glossary of open scholarship terms. Nat Hum Behav 6, 312--318 (2022). <https://doi.org/10.1038/s41562-021-01269-4>

Fillon, A., Lantian, A., Feldman, G., & N'Gbala, A. (2022). Exceptionality Effect in Agency Attributions: Exceptional Behaviors are Perceived as Higher Free will than Routine Behaviors. In International Review of Social Psychology (Vol. 35, Issue 1). Ubiquity Press, Ltd. <https://doi.org/10.5334/irsp.591>

# 2021

Brick, C., Fillon, A., Yeung, S. K., Wang, M., Lyu, H., Ho, J. Y. J., Wong, S. C., & Feldman, G. (2021). Self-interest Is Overestimated: Two Successful Pre-registered Replications and Extensions of Miller and Ratner (1998). In Collabra: Psychology (Vol. 7, Issue 1). University of California Press. <https://doi.org/10.1525/collabra.23443>

# 2020

Fillon, A., Kutscher, L., & Feldman, G. (2020). Impact of past behaviour normality: meta-analysis of exceptionality effect. In Cognition and Emotion (Vol. 35, Issue 1, pp. 129--149). Informa UK Limited. <https://doi.org/10.1080/02699931.2020.1816910>

# Preprints

Fillon, A.A., Girandola, F., Bonnardel, N., & Souchet, L. (2023) ["People systematically overlook subtractive changes: Replication and extension"](https://psyarxiv.com/4jkvn/download?format=pdf)

Fillon, A.A., Girandola, F., Bonnardel, N., Kenworthy, J., & Souchet, L. (2023) [Personal factors and group creativity characteristics: A correlational meta-analysis](https://psyarxiv.com/4br6a/download?format=pdf)

Fillon, A.A., Souchet, L. Pascual, A., Girandola, F. (accepted by meta psychology) [The effectiveness of the "But-you-are-free" technique: Meta-analysis and re-examination of the technique](https://psyarxiv.com/3ds26/download?format=pdf)

Fillon, A.A., Chandrashekar, P., & Feldman, G. (2023) [Asymmetries in attributions of blame and praise, intent, and causality:Free will, responsibility, and the side-effect effect](https://www.researchgate.net/publication/356831845_Asymmetries_in_attributions_of_blame_and_praise_intent_and_causality_Free_will_responsibility_and_the_side-effect_effect)

Jaubert, S., Fillon, A., Souchet, L., & Girandola, F. (2023) Vicarious dissonance: Pre-registred Meta-analysis. <https://osf.io/t5vs7/>

# Additional material

Fillon, A. A., Xiao, Q., Elsherif, M., Yeung, S. K., Nanakdewa, K., Protzko, J., Brick, C., Moreau, D., & Feldman, G. (2021). Correlational Meta-Analysis Registered Report Template. <https://osf.io/f85uy/>

Yeung, S. K., Fillon, A. A., Protzko, J., Elsherif, M., Xiao, Q., Pickering, J., & Feldman, G. (2021). Experimental Studies Meta-Analysis Registered Report Templates.<https://osf.io/ytgrp/>

Fillon, A.A. (2021, October). How to conduct a reproducible meta-analysis from open templates. Reproducibili'TEA Birmingham. <https://hal.archives-ouvertes.fr/hal-03426667>

Jaubert, S., Souchet, L., Fillon, A., & Girandola, F. (2021) [Dissonance vicariante et version radicale de la dissonance cognitive](https://hal.science/hal-03332123/)

Fillon, A.A. (2021). [Slow open science 2021 : Modèles de méta-analyses reproductibles](https://hal.science/hal-03426673/document)

Fillon, A.A. (2021). [Colloque Jeunes chercheurs 2021 : Modèles de méta-analyses reproductibles](https://hal.science/hal-03426662/document)
